#!/bin/sh

# Locally run job test of CI workflow in .github/workflows/test-and-report.yml. Helpful for debugging.
act -j test --env RUNTIME=ACT --env ACTIONS_RUNTIME_TOKEN=TOKEN --container-architecture linux/amd64 -P ubuntu-latest=catthehacker/ubuntu:act-latest --action-offline-mode --container-daemon-socket -
